### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by lezicai** [MIV-XJTU/JanusVLN#9]
Hello!
First of all, thank you for open-sourcing this project. However, I encountered some issues when running it, so I'm reaching out for help. After setting up the environment as required and running `bash scripts/evaluation.sh`, I got the following error. Upon checking, I found that the main problem is that `images_vggt` is `None` when passed to `forward` in `generate`, which causes an error in `images_vggt[i]` within the model. Do you have any solutions for this?

The error message on the problematic line reads:

```
[21:46:13.472627] /home/xyh/.conda/envs/janusvln/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/disk3/czl/JanusVLN/src/evaluation.py", line 492, in <module>
[rank0]:     eval()
[rank0]:   File "/data/disk3/czl/JanusVLN/src/evaluation.py", line 444, in eval
[rank0]:     evaluate(model, args)
[rank0]:   File "/data/disk3/czl/JanusVLN/src/evaluation.py", line 461, in evaluate
[rank0]:     sucs, spls, oss, ones, ep_num = evaluator.eval_action(get_rank())
[rank0]:   File "/data/disk3/czl/JanusVLN/src/evaluation.py", line 201, in eval_action
[rank0]:     action = self.model.call_model(images, episode_instruction,step_id)[0]
[rank0]:   File "/data/disk3/czl/JanusVLN/src/evaluation.py", line 388, in call_model
[rank0]:     cont = self.model.generate(
[rank0]:   File "/home/xyh/.conda/envs/janusvln/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/xyh/.conda/envs/janusvln/lib/python3.9/site-packages/transformers/generation/utils.py", line 2326, in generate
[rank0]:     result = self._sample(
[rank0]:   File "/home/xyh/.conda/envs/janusvln/lib/python3.9/site-packages/transformers/generation/utils.py", line 3286, in _sample
[rank0]:     outputs = self(**model_inputs, return_dict=True)
[rank0]:   File "/home/xyh/.conda/envs/janusvln/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/xyh/.conda/envs/janusvln/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/data/disk3/czl/JanusVLN/src/qwen_vl/model/modeling_qwen2_5_vl.py", line 1989, in forward
[rank0]:     if images_vggt[i].shape[0] > 0:
[rank0]: TypeError: 'NoneType' object is not subscriptable
scene EU6Fwq7SyZv:   0%|                                                                                                                                                                         | 0/132 [00:08<?, ?it/s]
[rank0]:[W1105 21:46:14.474828353 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
E1105 21:46:15.019524 499063 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 499096) of binary: /home/xyh/.conda/envs/janusvln/bin/python3.9
Traceback (most recent call last):
  File "/home/xyh/.conda/envs/janusvln/bin/torchrun", line 7, in <module>
    sys.exit(main())
  File "/home/xyh/.conda/envs/janusvln/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/xyh/.conda/envs/janusvln/lib/python3.9/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/home/xyh/.conda/envs/janusvln/lib/python3.9/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/xyh/.conda/envs/janusvln/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xyh/.conda/envs/janusvln/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
src/evaluation.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-11-05_21:46:15
  host      : robot-Z790-GAMING-X-AX
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 499096)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

As there is too much content, the complete log is attached. Looking forward to your reply!

[log.txt](https://github.com/user-attachments/files/23361456/log.txt)

**Comment by missTL** [comment]
It seems that the error occurred after you had been inferring for a while during the evaluation process, rather than at the very beginning. Please check whether the scene data of the episode where the error occurred is complete, and debug and look for the cause in that episode.

**Comment by lezicai** [comment]
> Thank you for pointing out the issue. Now I have fixed the bug. Additionally, since incorrect weights were previously uploaded, you need to re-download the [JanusVLN_Extra](https://www.modelscope.cn/models/misstl/JanusVLN_Extra) model.

Thank you for your efforts! I'll try the new weights!

**Comment by lezicai** [comment]
> Thank you for pointing out the issue. Now I have fixed the bug. Additionally, since incorrect weights were previously uploaded, you need to re-download the [JanusVLN_Extra](https://www.modelscope.cn/models/misstl/JanusVLN_Extra) model.

作者您好！我按照您说的重新下载了weights，并且重新克隆了源代码，确实没有再出现`NoneType`的问题了，但是我在4090GPU上运行时会爆显存，我尝试修改了`num_history`，`model_max_length`，`rgb_sensor`里的分辨率，但是都没有效果，导致我一直无法成功运行evaluation，请问您在evaluation时用的什么GPU？
```
[rank0]:   File "/home/xyh/.conda/envs/janusvln/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/xyh/.conda/envs/janusvln/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/data/disk3/czl/JanusVLN/src/qwen_vl/model/vggt/layers/rope.py", line 172, in forward
[rank0]:     return torch.cat((vertical_features, horizontal_features), dim=-1)
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 114.00 MiB. GPU 0 has a total capacity of 23.52 GiB of which 90.38 MiB is free. Including non-PyTorch memory, this process has 22.99 GiB memory in use. Of the allocated memory 20.46 GiB is allocated by PyTorch, and 1.22 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

**Comment by missTL** [comment]
About 40GB of video memory is needed. The video memory of the 4090 might not be sufficient to run the full version of JanusVLN.

**Comment by lezicai** [comment]
> About 40GB of video memory is needed. The video memory of the 4090 might not be sufficient to run the full version of JanusVLN.

OK, thank you for your reply anyway!
